/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'course-service-page-component': CourseServicePageComponent;
    'course-chapter-page-component': CourseChapterPageComponent;
    orders: Order;
    'session-bookings': SessionBooking;
    'session-settings': SessionSetting;
    'session-plans': SessionPlan;
    'user-subscriptions': UserSubscription;
    'support-messages': SupportMessage;
    'support-conversations': SupportConversation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'course-service-page-component': CourseServicePageComponentSelect<false> | CourseServicePageComponentSelect<true>;
    'course-chapter-page-component': CourseChapterPageComponentSelect<false> | CourseChapterPageComponentSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'session-bookings': SessionBookingsSelect<false> | SessionBookingsSelect<true>;
    'session-settings': SessionSettingsSelect<false> | SessionSettingsSelect<true>;
    'session-plans': SessionPlansSelect<false> | SessionPlansSelect<true>;
    'user-subscriptions': UserSubscriptionsSelect<false> | UserSubscriptionsSelect<true>;
    'support-messages': SupportMessagesSelect<false> | SupportMessagesSelect<true>;
    'support-conversations': SupportConversationsSelect<false> | SupportConversationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role?: ('student' | 'admin') | null;
  isVerified?: boolean | null;
  /**
   * Courses purchased by the user
   */
  purchasedCourses?: (string | CourseServicePageComponent)[] | null;
  firstSessionDiscountUsed?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Controls all content and styling for the course/service detail page layout (hero split, features grid, about/process section).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-service-page-component".
 */
export interface CourseServicePageComponent {
  id: string;
  /**
   * Main title for the page (also used to auto-generate slug)
   */
  title: string;
  /**
   * URL path (e.g. "web-development-masterclass")
   */
  slug: string;
  price: number;
  /**
   * Split-layout hero: image left, content right.
   */
  heroSection?: {
    /**
     * Background color of the entire hero section
     */
    sectionBackgroundColor?: string | null;
    /**
     * Left-column image (recommended: 800x900px or taller)
     */
    heroImage?: (string | null) | Media;
    heroImageAlt?: string | null;
    heroImageBackgroundColor?: string | null;
    /**
     * Decorative animated tile overlay on the hero image
     */
    showImageOverlayTiles?: boolean | null;
    /**
     * Exactly 4 tile colors for the overlay animation (_1 through _4)
     */
    overlayTileColors?:
      | {
          tileColor: string;
          id?: string | null;
        }[]
      | null;
    contentBackgroundColor?: string | null;
    eyebrow?: {
      show?: boolean | null;
      text?: string | null;
      textColor?: string | null;
      circleColor?: string | null;
      backgroundColor?: string | null;
    };
    heading?: string | null;
    headingColor?: string | null;
    subtext?: string | null;
    subtextColor?: string | null;
    subtextBackgroundColor?: string | null;
    /**
     * Drag to reorder buttons. Each button has its own style.
     */
    ctaButtons?:
      | {
          text: string;
          href?: string | null;
          openInNewTab?: boolean | null;
          variant?: ('accent' | 'secondary-dark' | 'primary' | 'outline' | 'ghost') | null;
          backgroundColor?: string | null;
          textColor?: string | null;
          borderColor?: string | null;
          hoverBackgroundColor?: string | null;
          hoverTextColor?: string | null;
          showArrowIcon?: boolean | null;
          arrowIconColor?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Grid of feature cards with headline, subheadline, CTA, and icon cards.
   */
  featuresSection?: {
    sectionBackgroundColor?: string | null;
    sectionPaddingTop?: string | null;
    sectionPaddingBottom?: string | null;
    headline?: {
      eyebrow?: {
        show?: boolean | null;
        text?: string | null;
        textColor?: string | null;
        circleColor?: string | null;
      };
      heading?: string | null;
      headingColor?: string | null;
      headlineBackgroundColor?: string | null;
      ctaButton?: {
        show?: boolean | null;
        text?: string | null;
        href?: string | null;
        openInNewTab?: boolean | null;
        backgroundColor?: string | null;
        textColor?: string | null;
        hoverBackgroundColor?: string | null;
        showArrowIcon?: boolean | null;
        arrowIconColor?: string | null;
      };
    };
    /**
     * Drag to reorder feature cards in the grid.
     */
    featureCards?:
      | {
          title: string;
          titleColor?: string | null;
          description?: string | null;
          descriptionColor?: string | null;
          /**
           * Paste full <svg>…</svg> markup for the card icon.
           */
          iconSvg?: string | null;
          /**
           * Applies as CSS currentColor to the SVG fill/stroke.
           */
          iconColor?: string | null;
          iconWrapBackgroundColor?: string | null;
          cardSize?: ('large' | 'small') | null;
          cardBackgroundColor?: string | null;
          cardBorderColor?: string | null;
          cardBorderRadius?: string | null;
          id?: string | null;
        }[]
      | null;
    skyBackground?: {
      show?: boolean | null;
      image?: (string | null) | Media;
      rotate?: boolean | null;
    };
  };
  /**
   * Large intro quote, a split image + step-by-step process list. Drag process steps to reorder.
   */
  aboutSection?: {
    sectionBackgroundColor?: string | null;
    introText?: string | null;
    introTextColor?: string | null;
    introBackgroundColor?: string | null;
    /**
     * Left-column image for the process list (horizontal crop)
     */
    processImage?: (string | null) | Media;
    processImageAlt?: string | null;
    processImageBackgroundColor?: string | null;
    /**
     * Drag to reorder steps.
     */
    processSteps?:
      | {
          stepTitle: string;
          stepTitleColor?: string | null;
          stepDescription?: string | null;
          stepDescriptionColor?: string | null;
          stepBackgroundColor?: string | null;
          stepBorderColor?: string | null;
          stepNumberShow?: boolean | null;
          stepNumberColor?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Page-wide defaults, SEO meta tags, and typography overrides.
   */
  pageSettings?: {
    pageBackgroundColor?: string | null;
    primaryTextColor?: string | null;
    accentColor?: string | null;
    /**
     * Leave blank to use the site default (e.g. "Inter, sans-serif")
     */
    fontFamily?: string | null;
    seo?: {
      /**
       * 60 characters recommended
       */
      metaTitle?: string | null;
      /**
       * 155–160 characters recommended
       */
      metaDescription?: string | null;
      /**
       * 1200x630px recommended
       */
      ogImage?: (string | null) | Media;
      /**
       * Comma-separated keywords
       */
      keywords?: string | null;
      /**
       * Leave blank to use the page URL automatically
       */
      canonicalUrl?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  /**
   * Cloudinary URL - use this in your frontend
   */
  cloudinary_url?: string | null;
  public_id?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Controls all content and styling for the course chapter detail page layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-chapter-page-component".
 */
export interface CourseChapterPageComponent {
  id: string;
  /**
   * Chapter title (used to auto-generate slug)
   */
  title: string;
  /**
   * URL path (e.g., "chapter-1-introduction")
   */
  slug: string;
  /**
   * Select which course this chapter belongs to
   */
  course: string | CourseServicePageComponent;
  /**
   * Controls chapter sequence inside the course
   */
  order: number;
  /**
   * Full-width hero with background image and course name heading.
   */
  heroSection?: {
    /**
     * Main heading displayed over the hero image
     */
    courseName?: string | null;
    courseNameColor?: string | null;
    /**
     * Hero background image (recommended: 1920x1080px)
     */
    backgroundImage?: (string | null) | Media;
    /**
     * Shown when no background image is set (hex or rgba)
     */
    backgroundColor?: string | null;
    /**
     * Semi-transparent overlay layered on top of background image
     */
    overlayTopColor?: string | null;
    /**
     * Gradient overlay at the bottom of the hero (for fade effect)
     */
    overlayBottomColor?: string | null;
    sectionBackgroundColor?: string | null;
    /**
     * Minimum height of the hero section (e.g. 480px, 60vh)
     */
    minHeight?: string | null;
  };
  /**
   * Left sidebar feature items and all draggable content blocks.
   */
  chapterInfoSection?: {
    sectionBackgroundColor?: string | null;
    sectionTextColor?: string | null;
    /**
     * Max width of the main content container
     */
    containerMaxWidth?: string | null;
    /**
     * Drag to reorder. Each item shows an icon, a label, and a value.
     */
    featureItems?:
      | {
          label: string;
          labelColor?: string | null;
          value: string;
          valueColor?: string | null;
          iconBackgroundColor?: string | null;
          iconColor?: string | null;
          itemBackgroundColor?: string | null;
          itemBorderColor?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Drag to reorder. Choose block type: Rich Text, Video, Image, or CTA Story.
     */
    contentBlocks?:
      | {
          blockType: 'richText' | 'video' | 'image' | 'ctaStory';
          /**
           * Supports headings, paragraphs, bold, italic, lists, etc.
           */
          richTextContent?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          richTextColor?: string | null;
          richTextBackgroundColor?: string | null;
          /**
           * Optional left-border accent color for the text block
           */
          richTextPaddingColor?: string | null;
          /**
           * Upload video through Media collection (Cloudinary)
           */
          video?: (string | null) | Media;
          videoCaption?: string | null;
          videoCaptionColor?: string | null;
          videoContainerBackgroundColor?: string | null;
          videoBorderColor?: string | null;
          videoAutoplay?: boolean | null;
          videoLoop?: boolean | null;
          videoMuted?: boolean | null;
          image?: (string | null) | Media;
          imageAlt?: string | null;
          imageCaption?: string | null;
          imageCaptionColor?: string | null;
          imageContainerBackgroundColor?: string | null;
          imageBorderColor?: string | null;
          imageObjectFit?: ('cover' | 'contain' | 'fill') | null;
          /**
           * Profile or instructor image shown on the left of the CTA card
           */
          ctaImage?: (string | null) | Media;
          ctaImageBackgroundColor?: string | null;
          /**
           * Small label with a dot shown above the heading
           */
          ctaEyebrowText?: string | null;
          ctaEyebrowTextColor?: string | null;
          /**
           * Color of the circular dot next to the eyebrow label
           */
          ctaEyebrowDotColor?: string | null;
          ctaHeading?: string | null;
          ctaHeadingColor?: string | null;
          ctaDescription?: string | null;
          ctaDescriptionColor?: string | null;
          /**
           * Drag to reorder links shown in the CTA card.
           */
          ctaLinks?:
            | {
                linkText: string;
                linkUrl: string;
                linkTextColor?: string | null;
                linkArrowColor?: string | null;
                linkBackgroundColor?: string | null;
                linkHoverBackgroundColor?: string | null;
                openInNewTab?: boolean | null;
                id?: string | null;
              }[]
            | null;
          ctaBackgroundColor?: string | null;
          ctaBorderColor?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Page-wide defaults, SEO, and typography.
   */
  pageSettings?: {
    pageBackgroundColor?: string | null;
    primaryTextColor?: string | null;
    accentColor?: string | null;
    /**
     * Leave blank to inherit from site globals (e.g. "Inter, sans-serif")
     */
    fontFamily?: string | null;
    seo?: {
      /**
       * 60 characters recommended
       */
      metaTitle?: string | null;
      /**
       * 155–160 characters recommended
       */
      metaDescription?: string | null;
      /**
       * 1200x630px recommended
       */
      ogImage?: (string | null) | Media;
      /**
       * Comma-separated keywords
       */
      keywords?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  user: string | User;
  course: string | CourseServicePageComponent;
  amount: number;
  status?: ('pending' | 'paid' | 'failed') | null;
  razorpayOrderId?: string | null;
  razorpayPaymentId?: string | null;
  razorpaySignature?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-bookings".
 */
export interface SessionBooking {
  id: string;
  user?: (string | null) | User;
  inviteeName: string;
  inviteeEmail: string;
  eventName?: string | null;
  startTime?: string | null;
  endTime?: string | null;
  meetingLink?: string | null;
  calendlyEventId?: string | null;
  cancelUrl?: string | null;
  rescheduleUrl?: string | null;
  isRescheduled?: boolean | null;
  rescheduledTo?: string | null;
  status?: ('pending' | 'booked' | 'cancelled' | 'completed') | null;
  /**
   * Date when booking was created
   */
  bookingDate?: string | null;
  sessionNotes?: string | null;
  bookingSource?: ('single' | 'subscription') | null;
  subscription?: (string | null) | UserSubscription;
  paymentStatus?: ('pending' | 'paid' | 'failed') | null;
  amount?: number | null;
  razorpayOrderId?: string | null;
  razorpayPaymentId?: string | null;
  razorpaySignature?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-subscriptions".
 */
export interface UserSubscription {
  id: string;
  user: string | User;
  plan: string | SessionPlan;
  status?: ('active' | 'expired' | 'cancelled') | null;
  startDate: string;
  endDate: string;
  totalSessions: number;
  remainingSessions: number;
  paymentStatus?: ('paid' | 'pending' | 'failed') | null;
  amount?: number | null;
  razorpayOrderId?: string | null;
  razorpayPaymentId?: string | null;
  razorpaySignature?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-plans".
 */
export interface SessionPlan {
  id: string;
  title: string;
  description?: string | null;
  image?: (string | null) | Media;
  price: number;
  sessionsPerMonth: number;
  durationDays?: number | null;
  isPopular?: boolean | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-settings".
 */
export interface SessionSetting {
  id: string;
  title?: string | null;
  sessionPrice: number;
  currency?: string | null;
  sessionDuration?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-messages".
 */
export interface SupportMessage {
  id: string;
  conversation: string | SupportConversation;
  user: string | User;
  senderType: 'user' | 'admin';
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-conversations".
 */
export interface SupportConversation {
  id: string;
  user: string | User;
  userName?: string | null;
  userEmail?: string | null;
  subject: string;
  status?: ('open' | 'closed') | null;
  lastMessage?: string | null;
  lastMessageAt?: string | null;
  unreadByAdmin?: boolean | null;
  unreadByUser?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'course-service-page-component';
        value: string | CourseServicePageComponent;
      } | null)
    | ({
        relationTo: 'course-chapter-page-component';
        value: string | CourseChapterPageComponent;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'session-bookings';
        value: string | SessionBooking;
      } | null)
    | ({
        relationTo: 'session-settings';
        value: string | SessionSetting;
      } | null)
    | ({
        relationTo: 'session-plans';
        value: string | SessionPlan;
      } | null)
    | ({
        relationTo: 'user-subscriptions';
        value: string | UserSubscription;
      } | null)
    | ({
        relationTo: 'support-messages';
        value: string | SupportMessage;
      } | null)
    | ({
        relationTo: 'support-conversations';
        value: string | SupportConversation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  isVerified?: T;
  purchasedCourses?: T;
  firstSessionDiscountUsed?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  cloudinary_url?: T;
  public_id?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-service-page-component_select".
 */
export interface CourseServicePageComponentSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  price?: T;
  heroSection?:
    | T
    | {
        sectionBackgroundColor?: T;
        heroImage?: T;
        heroImageAlt?: T;
        heroImageBackgroundColor?: T;
        showImageOverlayTiles?: T;
        overlayTileColors?:
          | T
          | {
              tileColor?: T;
              id?: T;
            };
        contentBackgroundColor?: T;
        eyebrow?:
          | T
          | {
              show?: T;
              text?: T;
              textColor?: T;
              circleColor?: T;
              backgroundColor?: T;
            };
        heading?: T;
        headingColor?: T;
        subtext?: T;
        subtextColor?: T;
        subtextBackgroundColor?: T;
        ctaButtons?:
          | T
          | {
              text?: T;
              href?: T;
              openInNewTab?: T;
              variant?: T;
              backgroundColor?: T;
              textColor?: T;
              borderColor?: T;
              hoverBackgroundColor?: T;
              hoverTextColor?: T;
              showArrowIcon?: T;
              arrowIconColor?: T;
              id?: T;
            };
      };
  featuresSection?:
    | T
    | {
        sectionBackgroundColor?: T;
        sectionPaddingTop?: T;
        sectionPaddingBottom?: T;
        headline?:
          | T
          | {
              eyebrow?:
                | T
                | {
                    show?: T;
                    text?: T;
                    textColor?: T;
                    circleColor?: T;
                  };
              heading?: T;
              headingColor?: T;
              headlineBackgroundColor?: T;
              ctaButton?:
                | T
                | {
                    show?: T;
                    text?: T;
                    href?: T;
                    openInNewTab?: T;
                    backgroundColor?: T;
                    textColor?: T;
                    hoverBackgroundColor?: T;
                    showArrowIcon?: T;
                    arrowIconColor?: T;
                  };
            };
        featureCards?:
          | T
          | {
              title?: T;
              titleColor?: T;
              description?: T;
              descriptionColor?: T;
              iconSvg?: T;
              iconColor?: T;
              iconWrapBackgroundColor?: T;
              cardSize?: T;
              cardBackgroundColor?: T;
              cardBorderColor?: T;
              cardBorderRadius?: T;
              id?: T;
            };
        skyBackground?:
          | T
          | {
              show?: T;
              image?: T;
              rotate?: T;
            };
      };
  aboutSection?:
    | T
    | {
        sectionBackgroundColor?: T;
        introText?: T;
        introTextColor?: T;
        introBackgroundColor?: T;
        processImage?: T;
        processImageAlt?: T;
        processImageBackgroundColor?: T;
        processSteps?:
          | T
          | {
              stepTitle?: T;
              stepTitleColor?: T;
              stepDescription?: T;
              stepDescriptionColor?: T;
              stepBackgroundColor?: T;
              stepBorderColor?: T;
              stepNumberShow?: T;
              stepNumberColor?: T;
              id?: T;
            };
      };
  pageSettings?:
    | T
    | {
        pageBackgroundColor?: T;
        primaryTextColor?: T;
        accentColor?: T;
        fontFamily?: T;
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              ogImage?: T;
              keywords?: T;
              canonicalUrl?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "course-chapter-page-component_select".
 */
export interface CourseChapterPageComponentSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  course?: T;
  order?: T;
  heroSection?:
    | T
    | {
        courseName?: T;
        courseNameColor?: T;
        backgroundImage?: T;
        backgroundColor?: T;
        overlayTopColor?: T;
        overlayBottomColor?: T;
        sectionBackgroundColor?: T;
        minHeight?: T;
      };
  chapterInfoSection?:
    | T
    | {
        sectionBackgroundColor?: T;
        sectionTextColor?: T;
        containerMaxWidth?: T;
        featureItems?:
          | T
          | {
              label?: T;
              labelColor?: T;
              value?: T;
              valueColor?: T;
              iconBackgroundColor?: T;
              iconColor?: T;
              itemBackgroundColor?: T;
              itemBorderColor?: T;
              id?: T;
            };
        contentBlocks?:
          | T
          | {
              blockType?: T;
              richTextContent?: T;
              richTextColor?: T;
              richTextBackgroundColor?: T;
              richTextPaddingColor?: T;
              video?: T;
              videoCaption?: T;
              videoCaptionColor?: T;
              videoContainerBackgroundColor?: T;
              videoBorderColor?: T;
              videoAutoplay?: T;
              videoLoop?: T;
              videoMuted?: T;
              image?: T;
              imageAlt?: T;
              imageCaption?: T;
              imageCaptionColor?: T;
              imageContainerBackgroundColor?: T;
              imageBorderColor?: T;
              imageObjectFit?: T;
              ctaImage?: T;
              ctaImageBackgroundColor?: T;
              ctaEyebrowText?: T;
              ctaEyebrowTextColor?: T;
              ctaEyebrowDotColor?: T;
              ctaHeading?: T;
              ctaHeadingColor?: T;
              ctaDescription?: T;
              ctaDescriptionColor?: T;
              ctaLinks?:
                | T
                | {
                    linkText?: T;
                    linkUrl?: T;
                    linkTextColor?: T;
                    linkArrowColor?: T;
                    linkBackgroundColor?: T;
                    linkHoverBackgroundColor?: T;
                    openInNewTab?: T;
                    id?: T;
                  };
              ctaBackgroundColor?: T;
              ctaBorderColor?: T;
              id?: T;
            };
      };
  pageSettings?:
    | T
    | {
        pageBackgroundColor?: T;
        primaryTextColor?: T;
        accentColor?: T;
        fontFamily?: T;
        seo?:
          | T
          | {
              metaTitle?: T;
              metaDescription?: T;
              ogImage?: T;
              keywords?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  user?: T;
  course?: T;
  amount?: T;
  status?: T;
  razorpayOrderId?: T;
  razorpayPaymentId?: T;
  razorpaySignature?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-bookings_select".
 */
export interface SessionBookingsSelect<T extends boolean = true> {
  user?: T;
  inviteeName?: T;
  inviteeEmail?: T;
  eventName?: T;
  startTime?: T;
  endTime?: T;
  meetingLink?: T;
  calendlyEventId?: T;
  cancelUrl?: T;
  rescheduleUrl?: T;
  isRescheduled?: T;
  rescheduledTo?: T;
  status?: T;
  bookingDate?: T;
  sessionNotes?: T;
  bookingSource?: T;
  subscription?: T;
  paymentStatus?: T;
  amount?: T;
  razorpayOrderId?: T;
  razorpayPaymentId?: T;
  razorpaySignature?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-settings_select".
 */
export interface SessionSettingsSelect<T extends boolean = true> {
  title?: T;
  sessionPrice?: T;
  currency?: T;
  sessionDuration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "session-plans_select".
 */
export interface SessionPlansSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  image?: T;
  price?: T;
  sessionsPerMonth?: T;
  durationDays?: T;
  isPopular?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-subscriptions_select".
 */
export interface UserSubscriptionsSelect<T extends boolean = true> {
  user?: T;
  plan?: T;
  status?: T;
  startDate?: T;
  endDate?: T;
  totalSessions?: T;
  remainingSessions?: T;
  paymentStatus?: T;
  amount?: T;
  razorpayOrderId?: T;
  razorpayPaymentId?: T;
  razorpaySignature?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-messages_select".
 */
export interface SupportMessagesSelect<T extends boolean = true> {
  conversation?: T;
  user?: T;
  senderType?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-conversations_select".
 */
export interface SupportConversationsSelect<T extends boolean = true> {
  user?: T;
  userName?: T;
  userEmail?: T;
  subject?: T;
  status?: T;
  lastMessage?: T;
  lastMessageAt?: T;
  unreadByAdmin?: T;
  unreadByUser?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}